package:
  name: ptb-drivers
  version: {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: ..

{% set data = load_setup_py_data() %}

build:
  noarch: python
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_FULL_HASH", "")[:8] }}
  entry_points:
    # NOTE: conda-build cannot distinguish between console and gui scripts
    {% for entry_point_type, entry_points in data.get("entry_points", dict()).items() -%}
    {% for entry_point in entry_points -%}
    - {{ entry_point }}
    {% endfor %}
    {% endfor %}
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.5.3
    - setuptools
  run:
    - python >=3.5.3
    - pyusb
    - artiq

test:
  imports:
    - ptb.tcp

about:
  home: https://github.com/quartiq/ptb-drivers
  license: LGPL
  summary: 'Driver for PTB opticlock hardware'
